name: tab_switcher
description: Build your complex app around tabs just like Chrome for Android
version: 1.1.0
repository: https://github.com/nuc134r/tab_switcher

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_shadow_container: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
